spring:
  application:
    name: licensing-service

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/msa
    username: admin
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: env

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG