server:
  port: 8080
spring:
  application:
    name: "study"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

build:
  version: "3.0"

accounts:
  message: "계정 메시지"
  contactDetails:
    name: "이름"
    email: "이메일"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG